name: movix
description: "Application Movix"

version: 0.0.56

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  provider: ^6.1.1

  cupertino_icons: ^1.0.8
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  http: ^1.2.2
  url_launcher: ^6.3.1
  scrollable_positioned_list: ^0.3.8
  font_awesome_flutter: ^10.8.0
  audioplayers: ^6.1.0
  flutter_svg: ^2.0.16
  camera: ^0.10.5+2
  path_provider: ^2.0.15
  image: ^4.0.17
  package_info_plus: ^8.3.0
  dio: ^5.8.0+1
  open_filex: ^4.7.0
  image_picker: ^1.1.2
  android_intent_plus: ^5.3.0
  location: ^5.0.3
  get_it: ^8.0.3
  flutter_compass: ^0.8.1
  permission_handler: ^12.0.0+1
  device_info_plus: ^11.3.0
  flutter_map_tile_caching: ^10.0.0
  flutter_dotenv: ^5.2.1
  go_router: ^15.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_riverpod: ^2.5.1
  mobile_scanner: ^6.0.10
  scan_receiver:
    path: ./scan_receiver
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3
  build_runner: ^2.4.13
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
    - assets/sounds/basic/
    - assets/sounds/mario/
    - assets/sounds/minecraft/
    - assets/sounds/pokemon/
    - assets/sounds/streetfighter/
    - .env

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.png"
  remove_alpha_ios: true
  dark_mode_ios: true
  image_path_ios: "assets/images/logo.png"
  image_path_dark_ios: "assets/images/logo_dark.png"
  # Configuration pour le mode sombre Android
  adaptive_icon_background_dark: "#000000"
  adaptive_icon_foreground_dark: "assets/images/logo_dark.png"
  # Configuration supplémentaire pour Android
  adaptive_icon_padding: true
  min_sdk_android: 21