name: movix
description: "Application Movix"

version: 0.0.21

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  http: ^1.2.2
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1
  scrollable_positioned_list: ^0.3.8
  font_awesome_flutter: ^10.8.0
  audioplayers: ^6.1.0
  flutter_svg: ^2.0.16
  camera: ^0.10.5+2
  path_provider: ^2.0.15
  image: ^4.0.17
  intl: ^0.18.1
  rename_app: ^1.6.2
  package_info_plus: ^8.3.0
  dio: ^5.8.0+1
  open_filex: ^4.7.0
  image_picker: ^1.1.2
  android_intent_plus: ^5.3.0
  flutter_launcher_icons: ^0.14.3
  location: ^5.0.3
  get_it: ^8.0.3
  flutter_compass: ^0.8.1
  permission_handler: ^12.0.0+1
  device_info_plus: ^11.3.0
  flutter_map_tile_caching: ^10.0.0
  flutter_dotenv: ^5.2.1
  go_router: ^15.1.1
  mobile_scanner: ^6.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
    - assets/sounds/basic/
    - assets/sounds/mario/
    - .env

flutter_icons:
  android: false
  ios: true
  image_path: "assets/images/logo.png"